language: python

python: "2.7"

dist: trusty

git:
  depth: 3

install:
  - pip install numpy matplotlib

script:
  - ./langcmp -n 4 -l 5 -d 2 -i wordlists/top1000en.txt -v -o results.txt -s stats.txt -g histogram.txt
  - cat results.txt | grep "rather paper wanted rates later after"
  - cat stats.txt | grep "mean" | grep "1.586207"
  - cat histogram.txt | grep "0 0.359606"

notifications:
  email:
    recipients:
      - diego@assencio.com
    on_success: change
    on_failure: always
